# Generated by Django 6.0.2 on 2026-06-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_mantenimientovehiculo_repuestos_utilizados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repuesto',
            name='imagen',
            field=models.ImageField(blank=True, default='repuestos/default_repuesto.png', null=True, upload_to='repuestos/', verbose_name='Imagen del Repuesto'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='imagen',
            field=models.ImageField(blank=True, default='vehiculos/default_vehicle.png', null=True, upload_to='vehiculos/', verbose_name='Imagen del Vehículo'),
        ),
    ]
