# Generated by Django 6.0.2 on 2026-06-02 19:32

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_repuesto_imagen_alter_vehiculo_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='#FFFFFF', help_text='Selecciona el color del vehículo', image_field=None, max_length=25, null=True, samples=None, verbose_name='Color del Vehículo'),
        ),
    ]
