# Generated by Django on 2026-06-05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_vehiculo_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarcaVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Marca')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción Adicional')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ModeloVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Modelo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción Adicional')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos', to='inventario.marcavehiculo', verbose_name='Marca del Vehículo')),
            ],
            options={
                'verbose_name': 'Modelo de Vehículo',
                'verbose_name_plural': 'Modelos de Vehículos',
                'ordering': ['nombre'],
            },
        ),
    ]
