# Generated by Django 5.2.5

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_create_marca_vehiculo_modelos'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre del Tipo de Vehículo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción Adicional')),
            ],
            options={
                'verbose_name': 'Tipo de Vehículo',
                'verbose_name_plural': 'Tipos de Vehículos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='modelovehiculo',
            name='tipo_vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modelos', to='inventario.tipovehiculo', verbose_name='Tipo de Vehículo'),
        ),
    ]
