# Generated by Django 6.0.2 on 2026-06-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_tipovehiculo_modelovehiculo_tipo_vehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='marcavehiculo',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='modelovehiculo',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='tipovehiculo',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
