# Generated by Django 6.0.2 on 2026-06-05 17:05

import django.db.models.deletion
import inventario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_marcavehiculo_estado_modelovehiculo_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTransmision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre del Tipo de Transmisión')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción Adicional')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Tipo de Transmisión',
                'verbose_name_plural': 'Tipos de Transmisión',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='codigo_chasis',
            field=models.CharField(max_length=17, unique=True, validators=[inventario.models.validar_vin], verbose_name='Código de Chasis (VIN)'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='combustible',
            field=models.CharField(blank=True, choices=[('nafta', 'Nafta'), ('diesel', 'Diésel'), ('electrico', 'Eléctrico'), ('hibrido', 'Híbrido'), ('otro', 'Otro')], default='gasolina', max_length=50, null=True, verbose_name='Tipo de Combustible'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos', to='inventario.marcavehiculo', verbose_name='Marca del Vehículo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos', to='inventario.modelovehiculo', verbose_name='Modelo del Vehículo'),
        ),
    ]
