# Generated by Django 6.0.2 on 2026-06-05 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_tipotransmision_alter_vehiculo_codigo_chasis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='motorizacion',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='transmision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos', to='inventario.tipotransmision', verbose_name='Tipo de Transmisión'),
        ),
    ]
