# Generated by Django 6.0.2 on 2026-06-05 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_remove_vehiculo_motorizacion'),
    ]
    # Esta migración quedó duplicada respecto a 0011_remove_vehiculo_motorizacion
    # (ambas añadían el campo `transmision`). Para evitar crear la columna
    # dos veces en SQLite, dejamos esta migración como no-op ya que 0011
    # ya añade el campo correctamente.
    operations = []
