# Generated by Django 6.0.2 on 2026-06-05 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_vehiculo_transmision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repuesto',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventario.deposito', verbose_name='Depósito de Ubicación'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventario.deposito', verbose_name='Depósito de Ubicación'),
        ),
    ]
