# Generated by Django 6.0.2 on 2026-06-09 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_alter_repuesto_ubicacion_alter_vehiculo_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='marcavehiculo',
            name='pais_origen',
            field=models.CharField(blank=True, default='Korea del Sur', max_length=100, null=True, verbose_name='País de Origen'),
        ),
    ]
