# Generated by Django 6.0.2 on 2026-04-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad_usuarios', '0004_alter_permiso_options_empleado_fecha_contratacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='utilizado',
            field=models.BooleanField(default=False, verbose_name='Utilizado'),
        ),
    ]
