# Generated by Django 6.0.2 on 2026-06-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad_usuarios', '0006_permiso_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioperfil',
            name='Contrasena_temporal',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contraseña Temporal'),
        ),
    ]
