# Generated by Django 6.0.2 on 2026-06-09 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad_usuarios', '0007_usuarioperfil_contrasena_temporal'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioperfil',
            name='tema',
            field=models.CharField(choices=[('theme-default', 'Tema Predeterminado'), ('theme-dark', 'Modo Oscuro'), ('theme-light', 'Modo Claro'), ('theme-emerald', 'Verde'), ('theme-ocean', 'Ocean'), ('theme-sunset', 'Sunset')], default='theme-default', help_text='Preferencia de tema del usuario', max_length=50, verbose_name='Tema'),
        ),
    ]
