# Generated by Django 5.2.4 on 2025-08-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgenteTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Agente')),
                ('contacto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Persona de Contacto')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('ruc', models.CharField(max_length=20, unique=True, verbose_name='RUC o Identificador Fiscal')),
            ],
            options={
                'verbose_name': 'Agente de Transporte',
                'verbose_name_plural': 'Agentes de Transporte',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DespachanteAduana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Despachante')),
                ('contacto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Persona de Contacto')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('registro', models.CharField(max_length=50, unique=True, verbose_name='Número de Registro')),
            ],
            options={
                'verbose_name': 'Despachante de Aduana',
                'verbose_name_plural': 'Despachantes de Aduana',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Proveedor')),
                ('contacto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Persona de Contacto')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('ruc', models.CharField(max_length=20, unique=True, verbose_name='RUC o Identificador Fiscal')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TasaCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneda_origen', models.CharField(default='KRW', max_length=3, verbose_name='Moneda de Origen')),
                ('moneda_destino', models.CharField(default='PYG', max_length=3, verbose_name='Moneda de Destino')),
                ('valor', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Valor de la Tasa')),
                ('fecha_actualizacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Tasa de Cambio',
                'verbose_name_plural': 'Tasas de Cambio',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
    ]
