# Generated by Django 6.0.2 on 2026-06-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones_maestras', '0007_sucursal_empresa'),
        ('seguridad_usuarios', '0007_usuarioperfil_contrasena_temporal'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='cargos', to='seguridad_usuarios.rol', verbose_name='Roles Asociados'),
        ),
    ]
